name: megaline
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  graphql_flutter: ^5.0.1
  equatable: ^2.0.3
  google_fonts: ^2.3.1
  injectable: ^1.5.3
  get_it: ^7.2.0
  freezed_annotation: ^1.1.0
  rxdart: ^0.27.3
  freezed: ^1.1.1
  dartz: ^0.10.1
  dots_indicator: ^2.1.0
  json_serializable: ^6.1.4
  carousel_slider: ^4.0.0
  build_runner: ^2.1.7
  cached_network_image: ^3.2.0
  internet_connection_checker: ^0.0.1+3
  extended_image: ^6.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  injectable_generator: ^1.5.3
  
flutter:
  uses-material-design: true
  assets:
  - assets/